import { useState } from 'react';
import { useOutletContext } from 'react-router-dom';
import { generateReport, getDailySummaries } from '../services/api';
import { fmtDate, fmtCurrency } from '../utils/helpers';

export default function ReportsPage() {
  const { outletId } = useOutletContext();
  const [reportType, setReportType] = useState('DAILY');
  const [startDate, setStartDate] = useState(fmtDate());
  const [result, setResult] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState('');

  const handleGenerate = async () => {
    setGenerating(true);
    setError('');
    setResult(null);
    try {
      const { data } = await generateReport(outletId, reportType, startDate);
      setResult(data);
    } catch (err) {
      setError(err.response?.data?.detail || err.response?.data?.error || 'Failed to generate report');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div>
      <h2>Reports</h2>

      <div className="card">
        <h3>Generate AI Report</h3>
        <div className="flex-row" style={{ gap: 10, flexWrap: 'wrap', alignItems: 'end' }}>
          <label>
            Type
            <select value={reportType} onChange={(e) => setReportType(e.target.value)}>
              <option value="DAILY">Daily</option>
              <option value="WEEKLY">Weekly</option>
              <option value="MONTHLY">Monthly</option>
            </select>
          </label>
          <label>
            Date
            <input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} />
          </label>
          <button onClick={handleGenerate} disabled={generating}>
            {generating ? 'Generating...' : 'Generate Report'}
          </button>
        </div>

        {error && <p className="text-error" style={{ marginTop: 8 }}>{error}</p>}

        {result && (
          <div style={{ marginTop: 16 }}>
            <p>
              <strong>Generated by:</strong> {result.generated_by || 'AI'}
            </p>
            {result.cloudinary_url && (
              <p>
                <a href={result.cloudinary_url} target="_blank" rel="noopener noreferrer">
                  Download PDF Report
                </a>
              </p>
            )}
            {result.gpt_summary && (
              <div style={{ marginTop: 8 }}>
                <strong>Summary:</strong>
                <p>{result.gpt_summary}</p>
              </div>
            )}
            {result.insights?.length > 0 && (
              <div style={{ marginTop: 8 }}>
                <strong>Insights:</strong>
                <ul>
                  {result.insights.map((ins, i) => (
                    <li key={i}>{ins}</li>
                  ))}
                </ul>
              </div>
            )}
            {result.recommendations?.length > 0 && (
              <div style={{ marginTop: 8 }}>
                <strong>Recommendations:</strong>
                <ul>
                  {result.recommendations.map((rec, i) => (
                    <li key={i}>{rec}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
