import { useState } from 'react';
import { useOutletContext } from 'react-router-dom';
import { generateReport } from '../services/api';
import { fmtDate } from '../utils/helpers';
import { ROLES } from '../utils/AuthContext';

export default function ReportsPage() {
  const { outletId, role } = useOutletContext();
  const [reportType, setReportType] = useState('DAILY');
  const [startDate, setStartDate] = useState(fmtDate());
  const [result, setResult] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState('');

  /* Only MANAGER can view reports */
  if (role !== ROLES.MANAGER) {
    return (
      <div className="empty-state" style={{ marginTop: 40 }}>
        <h3>🔒 Access Denied</h3>
        <p>Reports are available to Managers only.</p>
      </div>
    );
  }

  const handleGenerate = async () => {
    setGenerating(true);
    setError('');
    setResult(null);
    try {
      const { data } = await generateReport(outletId, reportType, startDate);
      setResult(data);
    } catch (err) {
      setError(err.response?.data?.detail || err.response?.data?.error || 'Failed to generate report');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div>
      <h2>📊 Reports</h2>

      {/* ───── Generate report form ───── */}
      <div className="card">
        <h3>Generate AI Report</h3>
        <div className="flex-row" style={{ gap: 10, flexWrap: 'wrap', alignItems: 'end' }}>
          <label>
            Type
            <select value={reportType} onChange={(e) => setReportType(e.target.value)}>
              <option value="DAILY">Daily</option>
              <option value="WEEKLY">Weekly</option>
              <option value="MONTHLY">Monthly</option>
            </select>
          </label>
          <label>
            Date
            <input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} />
          </label>
          <button onClick={handleGenerate} disabled={generating}>
            {generating ? '⏳ Generating...' : 'Generate Report'}
          </button>
        </div>

        {generating && (
          <p className="text-hint" style={{ marginTop: 10 }}>
            This may take 15–30 seconds while AI analyses your outlet data...
          </p>
        )}

        {error && <p className="text-error" style={{ marginTop: 8 }}>{error}</p>}
      </div>

      {/* ───── Generated report result ───── */}
      {result && (
        <div className="card" style={{ marginTop: 16 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 8 }}>
            <h3 style={{ margin: 0 }}>📄 Generated Report</h3>
            <span
              className="badge"
              style={{
                background: result.status === 'COMPLETED' ? '#A5E2E2' : '#FFAFCC',
                color: '#2D2428',
                fontSize: 11,
              }}
            >
              {result.status === 'COMPLETED' ? '✓ Completed' : result.status}
            </span>
          </div>

          <p className="text-sm" style={{ color: 'var(--gray-500)', marginTop: 6 }}>
            {result.report_type} &middot; {result.start_date}
            {result.end_date && result.end_date !== result.start_date ? ` → ${result.end_date}` : ''}
            &nbsp;&middot;&nbsp;Generated by {result.generated_by || 'AI'}
          </p>

          {/* Executive Summary */}
          {result.gpt_summary && (
            <div style={{ marginTop: 16 }}>
              <strong style={{ fontSize: 13, color: 'var(--gray-700)' }}>Executive Summary</strong>
              <p style={{ marginTop: 4, fontSize: 13, lineHeight: 1.7, color: 'var(--gray-700)' }}>
                {result.gpt_summary}
              </p>
            </div>
          )}

          {/* Insights */}
          {result.insights?.length > 0 && (
            <div style={{ marginTop: 16 }}>
              <strong style={{ fontSize: 13, color: 'var(--gray-700)' }}>📌 Insights</strong>
              <ul style={{ margin: '6px 0 0 18px', fontSize: 13, lineHeight: 1.7, color: 'var(--gray-700)' }}>
                {result.insights.map((ins, i) => (
                  <li key={i}>{ins}</li>
                ))}
              </ul>
            </div>
          )}

          {/* Recommendations */}
          {result.recommendations?.length > 0 && (
            <div style={{ marginTop: 16 }}>
              <strong style={{ fontSize: 13, color: 'var(--gray-700)' }}>💡 Recommendations</strong>
              <ul style={{ margin: '6px 0 0 18px', fontSize: 13, lineHeight: 1.7, color: 'var(--gray-700)' }}>
                {result.recommendations.map((rec, i) => (
                  <li key={i}>{rec}</li>
                ))}
              </ul>
            </div>
          )}

          {/* PDF download */}
          {result.cloudinary_url && (
            <div style={{ marginTop: 16 }}>
              <a
                href={result.cloudinary_url}
                target="_blank"
                rel="noopener noreferrer"
                style={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  gap: 6,
                  padding: '8px 16px',
                  background: 'var(--te-cyan)',
                  color: '#2D2428',
                  borderRadius: 8,
                  fontSize: 13,
                  fontWeight: 600,
                  textDecoration: 'none',
                }}
              >
                📄 Download PDF Report
              </a>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
