# Generated by Django 5.2.11 on 2026-02-28 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospitality_group", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PRODUCE", "Fresh Produce"),
                            ("DAIRY", "Dairy Products"),
                            ("MEAT", "Meat & Poultry"),
                            ("DRY", "Dry Goods"),
                            ("BEVERAGE", "Beverages"),
                            ("SUPPLIES", "Kitchen Supplies"),
                        ],
                        default="DRY",
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("KG", "Kilograms"),
                            ("L", "Liters"),
                            ("PCS", "Pieces"),
                            ("BAGS", "Bags"),
                            ("BOXES", "Boxes"),
                        ],
                        default="KG",
                        max_length=10,
                    ),
                ),
                ("current_quantity", models.FloatField(default=0.0)),
                (
                    "reorder_threshold",
                    models.FloatField(
                        default=10.0, help_text="Alert when below this level"
                    ),
                ),
                (
                    "par_level",
                    models.FloatField(default=50.0, help_text="Ideal stock level"),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("last_restocked", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="hospitality_group.outlet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
                "ordering": ["outlet", "category", "name"],
                "indexes": [
                    models.Index(
                        fields=["outlet", "category"],
                        name="predictive__outlet__8ba4cd_idx",
                    )
                ],
                "unique_together": {("outlet", "name")},
            },
        ),
        migrations.CreateModel(
            name="SalesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "hour",
                    models.IntegerField(
                        help_text="Hour of day (0-23) for hourly patterns"
                    ),
                ),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "avg_ticket_size",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "avg_wait_time_minutes",
                    models.FloatField(
                        default=0.0, help_text="Average wait time for food"
                    ),
                ),
                (
                    "category_sales",
                    models.JSONField(
                        default=dict, help_text="Sales by category {category: amount}"
                    ),
                ),
                (
                    "top_items",
                    models.JSONField(
                        default=list, help_text="Top selling items for this period"
                    ),
                ),
                ("day_of_week", models.IntegerField(help_text="0=Monday, 6=Sunday")),
                ("is_holiday", models.BooleanField(default=False)),
                (
                    "weather_condition",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_data",
                        to="hospitality_group.outlet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Data",
                "verbose_name_plural": "Sales Data",
                "ordering": ["-date", "hour"],
                "indexes": [
                    models.Index(
                        fields=["outlet", "-date"],
                        name="predictive__outlet__86f009_idx",
                    ),
                    models.Index(
                        fields=["day_of_week"], name="predictive__day_of__84c41e_idx"
                    ),
                ],
                "unique_together": {("outlet", "date", "hour")},
            },
        ),
        migrations.CreateModel(
            name="StaffSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("MORNING", "Morning (6AM-2PM)"),
                            ("AFTERNOON", "Afternoon (2PM-10PM)"),
                            ("NIGHT", "Night (10PM-6AM)"),
                            ("SPLIT", "Split Shift"),
                        ],
                        default="MORNING",
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_confirmed", models.BooleanField(default=False)),
                ("checked_in", models.DateTimeField(blank=True, null=True)),
                ("checked_out", models.DateTimeField(blank=True, null=True)),
                (
                    "is_ai_suggested",
                    models.BooleanField(
                        default=False,
                        help_text="Shift suggested by AI based on predictions",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="hospitality_group.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Schedule",
                "verbose_name_plural": "Staff Schedules",
                "ordering": ["-date", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["staff", "-date"], name="predictive__staff_i_f3f272_idx"
                    ),
                    models.Index(
                        fields=["date", "shift"], name="predictive__date_5d9422_idx"
                    ),
                ],
                "unique_together": {("staff", "date", "shift")},
            },
        ),
    ]
