# Generated by Django 5.2 on 2026-02-12 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("factory_graph", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_y_coordinate",
                    models.FloatField(
                        help_text="Y-coordinate of the detection line in the video frame"
                    ),
                ),
                (
                    "active_status",
                    models.BooleanField(
                        default=True, help_text="Whether this zone is currently active"
                    ),
                ),
                (
                    "loop_count",
                    models.IntegerField(
                        default=0, help_text="Number of objects that crossed the line"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "machine_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_zones",
                        to="factory_graph.machinenode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detection Zone",
                "verbose_name_plural": "Detection Zones",
                "ordering": ["machine_node", "line_y_coordinate"],
            },
        ),
        migrations.CreateModel(
            name="VisionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        help_text="Type of object detected (e.g., apple, bottle)",
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "confidence_score",
                    models.FloatField(help_text="AI confidence score (0.0 - 1.0)"),
                ),
                (
                    "current_total",
                    models.IntegerField(
                        default=0, help_text="Cumulative count at this timestamp"
                    ),
                ),
                (
                    "machine_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vision_logs",
                        to="factory_graph.machinenode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vision Log",
                "verbose_name_plural": "Vision Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["machine_node", "-timestamp"],
                        name="vision_engi_machine_d186b4_idx",
                    )
                ],
            },
        ),
    ]
