"""
Django settings for twinengine_core project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
from urllib.parse import urlparse, parse_qsl

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ── Deployment environment detection ─────────────────────────
# DEPLOY_ENV: 'development' | 'staging' | 'production'
DEPLOY_ENV = os.getenv('DEPLOY_ENV', 'development')
IS_PRODUCTION = DEPLOY_ENV == 'production'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-dev-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',
    'django_filters',
    'drf_spectacular',
    'django_celery_beat',
    'django_celery_results',
    'axes',
    
    # Local apps
    'apps.hospitality_group',
    'apps.layout_twin',
    'apps.order_engine',
    'apps.predictive_core',
    'apps.insights_hub',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
    'twinengine_core.middleware.RequestAuditMiddleware',
]

ROOT_URLCONF = 'twinengine_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'twinengine_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

_DATABASE_URL = os.getenv('DATABASE_URL', 'sqlite:///db.sqlite3')

if _DATABASE_URL.startswith('sqlite'):
    # SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # PostgreSQL for staging / production
    tmpPostgres = urlparse(_DATABASE_URL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': tmpPostgres.path.lstrip('/'),
            'USER': tmpPostgres.username,
            'PASSWORD': tmpPostgres.password,
            'HOST': tmpPostgres.hostname,
            'PORT': tmpPostgres.port or 5432,
            'OPTIONS': dict(parse_qsl(tmpPostgres.query)),
            'CONN_MAX_AGE': 600 if IS_PRODUCTION else 0,  # persistent connections in prod
            'CONN_HEALTH_CHECKS': True,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv('TIME_ZONE', 'Asia/Kolkata')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # project-level static assets (if any)
] if (BASE_DIR / 'static').is_dir() else []

# WhiteNoise compressed + cached static file storage
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Media files (user-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ---------------------------------------------------------------
# Cloudinary Configuration (media storage for PDFs, images, etc.)
# ---------------------------------------------------------------
import cloudinary
import cloudinary.uploader
import cloudinary.api

CLOUDINARY_CLOUD_NAME = os.getenv('CLOUDINARY_CLOUD_NAME', '')
CLOUDINARY_API_KEY = os.getenv('CLOUDINARY_API_KEY', '')
CLOUDINARY_API_SECRET = os.getenv('CLOUDINARY_API_SECRET', '')

cloudinary.config(
    cloud_name=CLOUDINARY_CLOUD_NAME,
    api_key=CLOUDINARY_API_KEY,
    api_secret=CLOUDINARY_API_SECRET,
    secure=True,
)

# ---------------------------------------------------------------
# Azure OpenAI Configuration (GPT-4o report generation)
# ---------------------------------------------------------------
AZURE_OPENAI_KEY = os.getenv('AZURE_OPENAI_KEY', '')
AZURE_OPENAI_ENDPOINT = os.getenv('AZURE_OPENAI_ENDPOINT', '')
AZURE_OPENAI_DEPLOYMENT = os.getenv('AZURE_OPENAI_DEPLOYMENT', 'gpt-4o')
AZURE_OPENAI_API_VERSION = os.getenv('AZURE_OPENAI_API_VERSION', '2024-12-01-preview')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
# https://github.com/adamchainz/django-cors-headers
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173'
    ).split(',')
    if origin.strip()
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# CSRF Configuration
# Trusted origins for CSRF — must include your frontend URL(s)
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        'CSRF_TRUSTED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173'
    ).split(',')
    if origin.strip()
]

# ---------------------------------------------------------------
# Production Security Hardening (only when DEBUG=False)
# ---------------------------------------------------------------
if not DEBUG:
    # HTTPS / HSTS
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000          # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Cookies
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'

    # Content security
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

    # Proxy header (for Render / cloud deployments behind a load balancer)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Channels Configuration (WebSocket support)
ASGI_APPLICATION = 'twinengine_core.asgi.application'

_REDIS_URL = os.getenv('REDIS_URL', '')
if _REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [_REDIS_URL],
            },
        },
    }
else:
    # In-memory layer for local development (single-process only)
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ] + (
        ['rest_framework.renderers.BrowsableAPIRenderer'] if DEBUG else []
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # ── Throttling ──
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',
        'user': '120/minute',
        'auth': '10/minute',           # login / register
        'predictions': '60/minute',    # ML prediction endpoints
        'reports': '10/minute',        # heavy report generation
        'uploads': '20/minute',        # file uploads
        'training': '5/minute',        # model training
    },
}

# drf-spectacular Configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'TwinEngine Hospitality API',
    'DESCRIPTION': (
        'AI-powered digital twin backend for hospitality operations.\n\n'
        '**Features:** Floor layout management, real-time order lifecycle, '
        'ML-driven predictions (demand, footfall, revenue, staffing, inventory), '
        'AI-generated PDF reports, and Cloudinary media management.'
    ),
    'VERSION': '2.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': [
        {'name': 'Auth', 'description': 'JWT authentication & user management'},
        {'name': 'Brands', 'description': 'Restaurant group / chain management'},
        {'name': 'Outlets', 'description': 'Individual restaurant locations'},
        {'name': 'Staff', 'description': 'Staff profile management'},
        {'name': 'Layout - Nodes', 'description': 'Service nodes (tables, stations) for floor visualization'},
        {'name': 'Layout - Flows', 'description': 'Connections between service nodes'},
        {'name': 'Orders', 'description': 'Order lifecycle management'},
        {'name': 'Payments', 'description': 'Payment processing & logs'},
        {'name': 'Sales Data', 'description': 'Historical sales data for ML'},
        {'name': 'Inventory', 'description': 'Inventory item management'},
        {'name': 'Schedules', 'description': 'Staff scheduling'},
        {'name': 'Predictions', 'description': 'ML prediction endpoints (demand, footfall, revenue, etc.)'},
        {'name': 'Reports', 'description': 'AI-generated operational reports & daily summaries'},
        {'name': 'Uploads', 'description': 'Cloudinary file upload / delete'},
        {'name': 'Tasks', 'description': 'Celery background task status polling'},
    ],
    'ENUM_NAME_OVERRIDES': {
        'OrderStatusEnum': 'apps.order_engine.models.OrderTicket.STATUS_CHOICES',
        'PaymentStatusEnum': 'apps.order_engine.models.PaymentLog.STATUS_CHOICES',
        'NodeStatusEnum': 'apps.layout_twin.models.ServiceNode.STATUS_CHOICES',
        'ReportTypeEnum': 'apps.insights_hub.models.PDFReport.REPORT_TYPE_CHOICES',
        'ReportGenerationStatusEnum': 'apps.insights_hub.models.PDFReport.GENERATION_STATUS_CHOICES',
    },
}

# Simple JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# ---------------------------------------------------------------
# Logging Configuration
# ---------------------------------------------------------------
LOG_LEVEL = os.getenv('LOG_LEVEL', 'DEBUG' if DEBUG else 'INFO')

# Use stdout-only logging in containers (no file handlers)
_IN_CONTAINER = os.getenv('CONTAINER', '').lower() in ('1', 'true')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name} {module}.{funcName}:{lineno} — {message}',
            'style': '{',
        },
        'simple': {
            'format': '{asctime} [{levelname}] {message}',
            'style': '{',
        },
        'json': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '{asctime} [{levelname}] {name} — {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json' if IS_PRODUCTION else ('verbose' if DEBUG else 'simple'),
        },
        **({} if _IN_CONTAINER else {
            'file': {
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': BASE_DIR / 'logs' / 'twinengine.log',
                'maxBytes': 5 * 1024 * 1024,  # 5 MB
                'backupCount': 3,
                'formatter': 'verbose',
            },
            'audit_file': {
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': BASE_DIR / 'logs' / 'audit.log',
                'maxBytes': 10 * 1024 * 1024,  # 10 MB
                'backupCount': 5,
                'formatter': 'verbose',
            },
        }),
    },
    'root': {
        'handlers': ['console'] if _IN_CONTAINER else ['console', 'file'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console'] if _IN_CONTAINER else ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'] if _IN_CONTAINER else ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'apps': {
            'handlers': ['console'] if _IN_CONTAINER else ['console', 'file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'twinengine.audit': {
            'handlers': ['console'] if _IN_CONTAINER else ['console', 'audit_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'axes': {
            'handlers': ['console'] if _IN_CONTAINER else ['console', 'audit_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ---------------------------------------------------------------
# Celery Configuration (background task processing)
# ---------------------------------------------------------------
CELERY_BROKER_URL = _REDIS_URL or 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'django-db'          # django_celery_results
CELERY_RESULT_EXTENDED = True                 # store task args / kwargs in DB
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60             # hard kill after 30 min
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60        # soft warning at 25 min

# Celery Beat — periodic task schedule
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# ---------------------------------------------------------------
# Email Configuration — Mailtrap Sandbox
# ---------------------------------------------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'sandbox.smtp.mailtrap.io')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'c18bad0549e293')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'eab8483f4ebb55')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '2525'))
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@twinengine.io')

# ---------------------------------------------------------------
# Django Axes — Brute-force login protection
# ---------------------------------------------------------------
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]
AXES_FAILURE_LIMIT = 5                         # lock after 5 failed attempts
AXES_COOLOFF_TIME = timedelta(minutes=30)      # unlock after 30 min
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]  # lock by user+IP combo
AXES_RESET_ON_SUCCESS = True                   # reset counter on successful login
AXES_LOCKOUT_CALLABLE = None                   # use default 403 response
AXES_IPWARE_META_PRECEDENCE_ORDER = (          # header precedence for IP detection
    'HTTP_X_FORWARDED_FOR',
    'REMOTE_ADDR',
)

# ---------------------------------------------------------------
# Additional Security Settings
# ---------------------------------------------------------------
# Password minimum length (strengthened)
AUTH_PASSWORD_VALIDATORS[1] = {
    'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    'OPTIONS': {'min_length': 10},
}

# Session timeout
SESSION_COOKIE_AGE = 60 * 60 * 2               # 2 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# File upload limits
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB max request body
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB max file upload

