# Generated by Django 5.2 on 2026-02-12 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("manufacturers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Report date")),
                (
                    "cloudinary_url",
                    models.URLField(help_text="URL to the report PDF on Cloudinary"),
                ),
                (
                    "gpt_summary",
                    models.TextField(help_text="GPT-4o generated summary text"),
                ),
                (
                    "generation_type",
                    models.CharField(
                        choices=[("AUTO", "Automatic"), ("MANUAL", "Manual")],
                        default="AUTO",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_reports",
                        to="manufacturers.manufacturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Production Report",
                "verbose_name_plural": "Production Reports",
                "ordering": ["-date", "-created_at"],
                "unique_together": {("manufacturer", "date", "generation_type")},
            },
        ),
        migrations.CreateModel(
            name="ShiftLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date of the shift")),
                ("shift_start", models.TimeField(help_text="Shift start time")),
                ("shift_end", models.TimeField(help_text="Shift end time")),
                (
                    "total_units",
                    models.IntegerField(
                        default=0, help_text="Total units produced during shift"
                    ),
                ),
                (
                    "total_downtime",
                    models.FloatField(
                        default=0.0, help_text="Total downtime in minutes"
                    ),
                ),
                (
                    "anomaly_count",
                    models.IntegerField(
                        default=0, help_text="Number of anomalies detected"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_logs",
                        to="manufacturers.manufacturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift Log",
                "verbose_name_plural": "Shift Logs",
                "ordering": ["-date", "-shift_start"],
                "unique_together": {("manufacturer", "date", "shift_start")},
            },
        ),
    ]
