# Generated by Django 5.2.11 on 2026-02-28 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Brand/Chain Name", max_length=255),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True, help_text="Brand logo on Cloudinary", null=True
                    ),
                ),
                (
                    "corporate_id",
                    models.CharField(
                        help_text="Unique Corporate Identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Primary Contact Email", max_length=254
                    ),
                ),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("BASIC", "Basic"),
                            ("PRO", "Professional"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        default="BASIC",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Outlet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Outlet Name/Location", max_length=255),
                ),
                ("address", models.TextField(help_text="Full Address")),
                ("city", models.CharField(max_length=100)),
                (
                    "seating_capacity",
                    models.IntegerField(default=0, help_text="Total seating capacity"),
                ),
                ("opening_time", models.TimeField(help_text="Daily opening time")),
                ("closing_time", models.TimeField(help_text="Daily closing time")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outlets",
                        to="hospitality_group.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outlet",
                "verbose_name_plural": "Outlets",
                "ordering": ["brand", "name"],
                "unique_together": {("brand", "name")},
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("MANAGER", "Manager"),
                            ("WAITER", "Waiter"),
                            ("CHEF", "Chef"),
                            ("HOST", "Host/Hostess"),
                            ("CASHIER", "Cashier"),
                        ],
                        default="WAITER",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "is_on_shift",
                    models.BooleanField(default=False, help_text="Currently working"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="hospitality_group.outlet",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "ordering": ["outlet", "user__username"],
            },
        ),
    ]
