# Generated by Django 5.2.11 on 2026-02-28 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospitality_group", "0001_initial"),
        ("layout_twin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "party_size",
                    models.IntegerField(default=1, help_text="Number of guests"),
                ),
                (
                    "items",
                    models.JSONField(
                        default=list, help_text="List of menu items ordered"
                    ),
                ),
                ("special_requests", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLACED", "Order Placed"),
                            ("PREPARING", "Preparing"),
                            ("READY", "Ready for Pickup"),
                            ("SERVED", "Served"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLACED",
                        max_length=20,
                    ),
                ),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                ("served_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "table",
                    models.ForeignKey(
                        limit_choices_to={"node_type": "TABLE"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="layout_twin.servicenode",
                    ),
                ),
                (
                    "waiter",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["WAITER", "MANAGER"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders_served",
                        to="hospitality_group.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Ticket",
                "verbose_name_plural": "Order Tickets",
                "ordering": ["-placed_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CARD", "Credit/Debit Card"),
                            ("UPI", "UPI Payment"),
                            ("WALLET", "Digital Wallet"),
                            ("SPLIT", "Split Payment"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tip_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="order_engine.orderticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Log",
                "verbose_name_plural": "Payment Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="orderticket",
            index=models.Index(
                fields=["table", "-placed_at"], name="order_engin_table_i_a3ea45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderticket",
            index=models.Index(fields=["status"], name="order_engin_status_38bff3_idx"),
        ),
        migrations.AddIndex(
            model_name="orderticket",
            index=models.Index(
                fields=["waiter", "-placed_at"], name="order_engin_waiter__618681_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentlog",
            index=models.Index(
                fields=["order", "-created_at"], name="order_engin_order_i_8749e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentlog",
            index=models.Index(fields=["status"], name="order_engin_status_25d08a_idx"),
        ),
    ]
