# Generated by Django 5.2 on 2026-02-12 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("manufacturers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Machine type name (e.g., Roller, Grinder)",
                        max_length=100,
                    ),
                ),
                (
                    "model_3d_embed_code",
                    models.TextField(
                        help_text="Sketchfab or other 3D model embed code"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Machine description and capabilities",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Machine Type",
                "verbose_name_plural": "Machine Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MachineNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique machine instance name", max_length=150
                    ),
                ),
                (
                    "pos_x",
                    models.FloatField(
                        default=0.0, help_text="X coordinate in 3D space"
                    ),
                ),
                (
                    "pos_y",
                    models.FloatField(
                        default=0.0, help_text="Y coordinate in 3D space"
                    ),
                ),
                (
                    "pos_z",
                    models.FloatField(
                        default=0.0, help_text="Z coordinate in 3D space"
                    ),
                ),
                (
                    "video_feed_url",
                    models.URLField(
                        blank=True,
                        help_text="Cloudinary video URL or RTSP stream",
                        null=True,
                    ),
                ),
                (
                    "hf_endpoint",
                    models.URLField(
                        blank=True,
                        help_text="Hugging Face inference endpoint",
                        null=True,
                    ),
                ),
                (
                    "hf_key",
                    models.CharField(
                        blank=True,
                        help_text="Hugging Face API key",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("OFFLINE", "Offline"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machines",
                        to="manufacturers.manufacturer",
                    ),
                ),
                (
                    "machine_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="factory_graph.machinetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Machine Node",
                "verbose_name_plural": "Machine Nodes",
                "ordering": ["manufacturer", "name"],
                "unique_together": {("manufacturer", "name")},
            },
        ),
        migrations.CreateModel(
            name="MachineEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flow_type",
                    models.CharField(
                        choices=[
                            ("MATERIAL", "Material Flow"),
                            ("DATA", "Data Flow"),
                            ("CONTROL", "Control Signal"),
                        ],
                        default="MATERIAL",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="factory_graph.machinenode",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="factory_graph.machinenode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Machine Edge",
                "verbose_name_plural": "Machine Edges",
                "ordering": ["source_node", "target_node"],
                "unique_together": {("source_node", "target_node", "flow_type")},
            },
        ),
    ]
