# Generated by Django 5.2.11 on 2026-02-28 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospitality_group", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "avg_ticket_size",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_tips",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("total_guests", models.IntegerField(default=0)),
                (
                    "avg_table_turnover_time",
                    models.FloatField(
                        default=0.0, help_text="Average minutes per table session"
                    ),
                ),
                (
                    "avg_wait_time",
                    models.FloatField(
                        default=0.0, help_text="Average wait time in minutes"
                    ),
                ),
                (
                    "peak_hour",
                    models.IntegerField(
                        default=12, help_text="Hour with most orders (0-23)"
                    ),
                ),
                (
                    "peak_revenue",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "delayed_orders",
                    models.IntegerField(
                        default=0, help_text="Orders with wait > 15min"
                    ),
                ),
                ("cancelled_orders", models.IntegerField(default=0)),
                (
                    "sales_by_category",
                    models.JSONField(default=dict, help_text="Revenue by category"),
                ),
                (
                    "top_selling_items",
                    models.JSONField(default=list, help_text="Top 10 items sold"),
                ),
                ("staff_count", models.IntegerField(default=0)),
                (
                    "revenue_per_staff",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_summaries",
                        to="hospitality_group.outlet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Summary",
                "verbose_name_plural": "Daily Summaries",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["outlet", "-date"],
                        name="insights_hu_outlet__47d349_idx",
                    )
                ],
                "unique_together": {("outlet", "date")},
            },
        ),
        migrations.CreateModel(
            name="PDFReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily Operations Report"),
                            ("WEEKLY", "Weekly Summary"),
                            ("MONTHLY", "Monthly Analysis"),
                            ("CUSTOM", "Custom Report"),
                        ],
                        default="DAILY",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "cloudinary_url",
                    models.URLField(
                        blank=True, help_text="URL to the PDF on Cloudinary", null=True
                    ),
                ),
                (
                    "gpt_summary",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated executive summary",
                        null=True,
                    ),
                ),
                (
                    "insights",
                    models.JSONField(
                        default=list, help_text="List of AI-generated insights"
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list, help_text="Actionable recommendations"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("GENERATING", "Generating"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "generated_by",
                    models.CharField(
                        default="GPT-4", help_text="AI model used", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_reports",
                        to="hospitality_group.outlet",
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF Report",
                "verbose_name_plural": "PDF Reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["outlet", "-created_at"],
                        name="insights_hu_outlet__81260e_idx",
                    ),
                    models.Index(
                        fields=["status"], name="insights_hu_status_dfeb0d_idx"
                    ),
                ],
            },
        ),
    ]
