from django.contrib import admin
from django.utils.html import format_html
from .models import DailySummary, PDFReport


@admin.register(DailySummary)
class DailySummaryAdmin(admin.ModelAdmin):
    list_display = [
        'outlet', 'date', 'revenue_display', 'total_orders', 
        'total_guests', 'avg_wait_time', 'delayed_orders_display', 'created_at'
    ]
    list_filter = ['date', 'outlet', 'created_at']
    search_fields = ['outlet__name']
    raw_id_fields = ['outlet']
    date_hierarchy = 'date'
    ordering = ['-date']
    readonly_fields = ['created_at']
    
    fieldsets = (
        ('Summary Information', {
            'fields': ('outlet', 'date')
        }),
        ('Revenue & Orders', {
            'fields': ('total_revenue', 'total_orders', 'total_guests')
        }),
        ('Performance Metrics', {
            'fields': (
                'avg_wait_time', 'longest_wait_time', 
                'delayed_orders', 'cancelled_orders'
            )
        }),
        ('Operational Stats', {
            'fields': (
                'peak_hour', 'peak_hour_covers', 
                'total_tips', 'avg_party_size'
            ),
            'classes': ('collapse',)
        }),
        ('Metadata', {
            'fields': ('created_at',),
            'classes': ('collapse',)
        }),
    )
    
    def revenue_display(self, obj):
        """Format revenue with currency symbol."""
        return format_html('<strong>₹{:,.2f}</strong>', obj.total_revenue)
    revenue_display.short_description = 'Revenue'
    revenue_display.admin_order_field = 'total_revenue'
    
    def delayed_orders_display(self, obj):
        """Highlight delayed orders in red if > 0."""
        if obj.delayed_orders > 0:
            return format_html(
                '<span style="color: red; font-weight: bold;">⚠ {}</span>',
                obj.delayed_orders
            )
        return obj.delayed_orders
    delayed_orders_display.short_description = 'Delayed'
    delayed_orders_display.admin_order_field = 'delayed_orders'


@admin.register(PDFReport)
class PDFReportAdmin(admin.ModelAdmin):
    list_display = [
        'id', 'outlet', 'report_type_badge', 'date_range', 
        'status_badge', 'has_pdf', 'created_at'
    ]
    list_filter = ['report_type', 'status', 'outlet', 'created_at']
    search_fields = ['outlet__name', 'gpt_summary', 'insights']
    raw_id_fields = ['outlet']
    ordering = ['-created_at']
    readonly_fields = ['created_at']
    
    fieldsets = (
        ('Report Information', {
            'fields': ('outlet', 'report_type', 'start_date', 'end_date', 'status')
        }),
        ('AI-Generated Content', {
            'fields': ('gpt_summary', 'insights', 'recommendations'),
            'description': 'Content generated by Azure GPT-4o'
        }),
        ('Report File', {
            'fields': ('cloudinary_url',)
        }),
        ('Metadata', {
            'fields': ('generated_by', 'error_message', 'created_at'),
            'classes': ('collapse',)
        }),
    )
    
    def report_type_badge(self, obj):
        """Color-coded report type badge."""
        colors = {
            'DAILY': '#3498db',       # Blue
            'WEEKLY': '#2ecc71',      # Green
            'MONTHLY': '#9b59b6',     # Purple
            'CUSTOM': '#e67e22',      # Orange
        }
        color = colors.get(obj.report_type, '#95a5a6')
        return format_html(
            '<span style="background-color: {}; color: white; padding: 3px 8px; border-radius: 3px;">{}</span>',
            color,
            obj.get_report_type_display()
        )
    report_type_badge.short_description = 'Type'
    report_type_badge.admin_order_field = 'report_type'
    
    def status_badge(self, obj):
        """Color-coded status badge."""
        colors = {
            'PENDING': '#f39c12',     # Orange
            'GENERATING': '#3498db',  # Blue
            'COMPLETED': '#2ecc71',   # Green
            'FAILED': '#e74c3c',      # Red
        }
        color = colors.get(obj.status, '#95a5a6')
        return format_html(
            '<span style="background-color: {}; color: white; padding: 3px 8px; border-radius: 3px;">{}</span>',
            color,
            obj.get_status_display()
        )
    status_badge.short_description = 'Status'
    status_badge.admin_order_field = 'status'
    
    def date_range(self, obj):
        """Display date range for the report."""
        return f"{obj.start_date} to {obj.end_date}"
    date_range.short_description = 'Date Range'
    
    def has_pdf(self, obj):
        """Indicate if PDF file is available."""
        return bool(obj.cloudinary_url)
    has_pdf.short_description = 'PDF Available'
    has_pdf.boolean = True
