# Generated by Django 5.2.11 on 2026-02-28 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospitality_group", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Node identifier (e.g., Table-1, Kitchen-Main)",
                        max_length=100,
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("TABLE", "Table"),
                            ("KITCHEN", "Kitchen Station"),
                            ("WASH", "Washing Station"),
                            ("BAR", "Bar Counter"),
                            ("ENTRY", "Entry/Reception"),
                        ],
                        default="TABLE",
                        max_length=20,
                    ),
                ),
                (
                    "pos_x",
                    models.FloatField(
                        default=0.0, help_text="X coordinate in 3D space"
                    ),
                ),
                (
                    "pos_y",
                    models.FloatField(
                        default=0.0, help_text="Y coordinate in 3D space"
                    ),
                ),
                (
                    "pos_z",
                    models.FloatField(
                        default=0.0, help_text="Z coordinate in 3D space"
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        default=4, help_text="Seating capacity (for tables)"
                    ),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("BLUE", "Empty / Ready"),
                            ("RED", "Occupied - Waiting"),
                            ("GREEN", "Occupied - Served"),
                            ("YELLOW", "Issue / Delay"),
                            ("GREY", "Maintenance / Reserved"),
                        ],
                        default="BLUE",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_nodes",
                        to="hospitality_group.outlet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Node",
                "verbose_name_plural": "Service Nodes",
                "ordering": ["outlet", "name"],
                "unique_together": {("outlet", "name")},
            },
        ),
        migrations.CreateModel(
            name="ServiceFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flow_type",
                    models.CharField(
                        choices=[
                            ("FOOD_DELIVERY", "Food Delivery"),
                            ("DISH_RETURN", "Dish Return"),
                            ("ORDER_PATH", "Order Path"),
                            ("CUSTOMER_FLOW", "Customer Flow"),
                        ],
                        default="FOOD_DELIVERY",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_flows",
                        to="layout_twin.servicenode",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_flows",
                        to="layout_twin.servicenode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Flow",
                "verbose_name_plural": "Service Flows",
                "ordering": ["source_node", "target_node"],
                "unique_together": {("source_node", "target_node", "flow_type")},
            },
        ),
    ]
