# Generated by Django 5.2 on 2026-02-12 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("factory_graph", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(help_text="Temperature reading in Celsius"),
                ),
                (
                    "vibration",
                    models.FloatField(
                        help_text="Vibration level (arbitrary units or Hz)"
                    ),
                ),
                ("torque", models.FloatField(help_text="Torque reading in Nm")),
                ("rpm", models.FloatField(help_text="Rotations per minute")),
                (
                    "tool_wear",
                    models.FloatField(
                        help_text="Tool wear indicator (0-1 scale or minutes)"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "machine_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_data",
                        to="factory_graph.machinenode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sensor Data",
                "verbose_name_plural": "Sensor Data",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AnomalyAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_prediction",
                    models.CharField(
                        help_text="ML model prediction (e.g., 'ANOMALY', 'NORMAL')",
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "resolved_status",
                    models.BooleanField(
                        default=False, help_text="Whether this alert has been resolved"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Engineer notes or resolution details",
                        null=True,
                    ),
                ),
                (
                    "sensor_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomaly_alerts",
                        to="sensors.sensordata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anomaly Alert",
                "verbose_name_plural": "Anomaly Alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="sensordata",
            index=models.Index(
                fields=["machine_node", "-timestamp"],
                name="sensors_sen_machine_18a95f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="anomalyalert",
            index=models.Index(
                fields=["sensor_data", "-created_at"],
                name="sensors_ano_sensor__bb0672_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="anomalyalert",
            index=models.Index(
                fields=["resolved_status"], name="sensors_ano_resolve_4be3bb_idx"
            ),
        ),
    ]
